### ISSUE TITLE
Email verification: Send email with code to the user

### ISSUE THREAD

**Issue by oed** [3box/3box-verifications#14]
Implement the spec produced from #13

Likely:
1. ingest email address and DID
2. send email and 6 digit code to email address (server keeps the initial DID)

**Comment by c-castillo** [comment]
Some assumptions:

1) The code will expire in X minutes (Like most of the services does)
2) Code gets calculated by
3) Delivery of the code will be handled by using Amazon simple email service

**Comment by michaelsena** [comment]
The email message can be found in this story, in the linked Notion doc

https://github.com/3box/3box-verifications/issues/15
@c-castillo
