### ISSUE TITLE
504 Error for confirmation that code sent, and for sending the code to be verified

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-verifications#47]
I think we're having the same issue as before with the email server
The verification email is properly sent, but no response is sent back
The same 504 timeout error for when I send the code

The actual verification doesn't seem to work - when I reload dapp, my email does not show as verified.![Screen Shot 2019-04-17 at 5.19.27 PM.png](https://images.zenhubusercontent.com/5b86d3797f25530fa3d54999/4444c91b-44f9-4f76-a554-b94a1094aed7)

**Comment by oed** [comment]
The 504 error should be fixed now.
