### ISSUE TITLE
Redesign the way we use redis store in the EmailMgr

### ISSUE THREAD

**Issue by lsenta** [3box/3box-verifications#51]
Currently, the code takes a redis store as a parameter:
https://github.com/3box/3box-verifications/blob/develop/src/lib/emailMgr.js#L10

And will override it when it accesses the store:
https://github.com/3box/3box-verifications/blob/develop/src/lib/emailMgr.js#L108

We should refactor this code, either remove the parameter completely or implement the getStoredX / storeX correctly.

**Comment by oed** [comment]
Stale, closing.
