### ISSUE TITLE
Change text of twitter verification

### ISSUE THREAD

**Issue by dazuck** [3box/3box-verifications#69]
MS to decide copy & priority. Draft take below: 

This tweet links my Twitter account to my ~3Box profile~ 3ID.

[DID]

~Web3 social profiles ~ Portable data, reputation and profiles by 
@3boxdb.

[3box profile link]

**Comment by oed** [comment]
Yeah, let's do this as we update to 3ID everywhere. I.e. we also get rid of the muport DID in the tweet.
