### ISSUE TITLE
3ID not working in Twitter verifications API

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-verifications#81]
In attempting to move from muport did to 3ID with:
```      
const response = await fetch('https://verifications.3box.io/twitter', {
        method: 'POST',
        body: JSON.stringify({
          did: threeId,
          twitter_handle: `${verifiedTwitter}`,
        }),
      });
```
Am getting the error:
`Uncaught (in promise) Error: Verification not valid for given user
    at verifier.js:119`

Despite getting back the claim: 
```
{
   status: "success",
   data: {
         verification: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJpYXQiOjE1Nzg1OTgxMDksInN1YiI6ImRpZDozOmJhZnlyZWljaXFuNWlsdHNlN3NyYzM3Y3R2aGhyNDMzemNsd212aHFvZDRkeHVrcXdsZXkyZTdtZnFxIiwiY2xhaW0iOnsidHdpdHRlcl9oYW5kbGUiOiJnb25nc2hvd2tub3dzIiwidHdpdHRlcl9wcm9vZiI6Imh0dHBzOi8vdHdpdHRlci5jb20vZ29uZ3Nob3drbm93cy9zdGF0dXMvMTIxNTAwNjk5NDIwNzMyMjExNSJ9LCJpc3MiOiJkaWQ6aHR0cHM6dmVyaWZpY2F0aW9ucy4zYm94LmlvIn0.ica47f5zAh3CaNLabMEcpuNxETvwwjjuxh1yfASaYH9TfeO5zzOM59orl9NDJnNTzUr-Ef_sZ9unI6k7MhnvEA"
   }
}
```
with 3id:
`did:3:bafyreiciqn5iltse7src37ctvhhr433zclwmvhqod4dxukqwley2e7mfqq`

**Comment by zachferland** [comment]
where are you getting the error? when the req returns a response looks good

**Comment by oznekenzo** [comment]
takes a little time since I have to deploy then test from one of our live urls but im guessing from: 
`const twitterUsername = await box.verified.addTwitter(claim.data.verification);`

**Comment by oznekenzo** [comment]
The `verifyTwitter` method in 3box/lib/utils/verifier.js

**Comment by zachferland** [comment]
@oed for tmrrw, nothing to do here, just have to update 3box-js in dapp same time the tweet is changed. 3box-js update will verify both a 3id and muport verification (passes the array of dids), but yeah for adding a new verification to store, it just expects a 3id (which seems like a good constraint, or wont come up anywhere else anyways)

**Comment by oed** [comment]
I'm confused. I thought @oznekenzo was using the update library when testing this?

**Comment by zachferland** [comment]
no, think was 1.14 or something, is the expectation to test in dapp before releasing? doesnt sound like block

**Comment by oed** [comment]
@zachferland how is that possible? I thought you would only get the 3ID from `box.DID` in the 1.16 beta?

**Comment by zachferland** [comment]
you do, 1.14 was used here i believe

**Comment by oed** [comment]
Really ok, then that makes sense :) @oznekenzo Can you just try this with the latest beta?

**Comment by oznekenzo** [comment]
Had thought this was updated in the lib long ago so didnt realize I needed to use the beta lib.  All working now, thanks guys
